### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by wkdtjdwns** [wkdtjdwns/STG-2007#5]
**플레이어 이동 구현 (W, A, S, D를 사용함.)**

**Comment by dbsrjs** [comment]
# 캐릭터 이동

- `GetAxisRaw`를 사용해서 입력을 받아옴.
- `Rigidbody`를 사용해서 입력 받아온 위치로 이동
- `Input.GetButton("Run")` 을 사용해서 left shift 를 누르면 캐릭터가 달리기를 함.
- `transform.LookAt`을 사용해서 이동한 곳을 바라보록 함.

**Comment by dbsrjs** [comment]
# 캐릭터 이동 로직 수정

- 기본에 `Rigidbody` 를 사용해서 이동하던 것을 `charactercontroller`라는 컴포넌트를 사용하는 것으로 바꿈.
- 점프 로직을 추가함
