### ISSUE TITLE
Item Use

### ISSUE THREAD

**Issue by wkdtjdwns** [wkdtjdwns/STG-2007#7]
**아이템을 사용하는 로직 구현 (아직 아이템 구현이 되지 않았으므로 구현만 하며, 1, 2, 3, 4와 같이 숫자 키로 사용할 수 있게 함.)**

**Comment by tlavksdmlskf** [comment]
# 아이템 사용

- GetKeyDown를 사용해서 입력을 받아옴.
- 아직은 아이템이 구현이 안되어서 구현만 함

**Comment by dbsrjs** [comment]
# 아이템 사용 소스 리펙토링
가독성을 위한 코드 변경
